### ISSUE TITLE
Feature request: Allow YAML assertions

### ISSUE THREAD

**Issue by cybershoe** [F5Networks/f5-appsvcs-extension#109]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
```
Any
```

##### BIGIP VERSION
```
Any
```

##### SUMMARY

Some users prefer YAML to JSON. As JSON is a subset of YAML, we should parse and accept declarations in both JSON and YAML formats.

**Comment by focrensh** [comment]
Please use an orchestration tool to do this conversion. One example would be ansible to_json filter or built in with URI.

```
    - name: YAML to JSON declaration
      uri:
        url: https://{{ bigip }}/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "token"
        body:
          class: AS3
          action: deploy
          persist: true
          declaration:
            class: ADC
            schemaVersion: 3.10
            id: example-declaration-01
            label: Task1
            remark: Task 1 - HTTP Application Service
            Tenant1:
              class: Tenant
              MyWebApp1http:
                class: Application
                template: http
                serviceMain:
                  class: Service_HTTP
                  virtualAddresses:
                  - "10.1.1.1"
                  pool: web_pool
                web_pool:
                  class: Pool
                  monitors:
                  - http
                  members:
                  - servicePort: 80
                    serverAddresses:
                    - "10.2.2.2"
                    shareNodes: true
        body_format: json
```
