### ISSUE TITLE
f5-as3-container 422 when used with k8s-bigip-ctlr 

### ISSUE THREAD

**Issue by andrijaperovic** [F5Networks/f5-appsvcs-extension#354]
### Environment
 * Application Services Version: 
```
curl -vku "user:password" -X GET http://localhost:8100/mgmt/shared/appsvcs/info
{"version":"3.22.0","release":"2","schemaCurrent":"3.22.0","schemaMinimum":"3.0.0"}
```
Big-IP Controller: v2.1.1
f5-as3-container version: 3.22.0

 * BIG-IP Version:  15.1.0.4 Build 0.0.6 Point Release 4 

### Summary
When exposing f5-as3-container as kubernetes service and updating the bigip-login to point to the IP of the kubernetes service which exposes f5-as3-container container, there is a 422 response which is generated, which is not reproducible when generating the same request from the k8s-big-ip-ctlr container command line using curl. 

### Steps To Reproduce
1. Create the following configmap in your target namespace where Big-IP controller is deployed:
```json
apiVersion: v1
data:
  template: |
    {
            "class": "AS3",
            "action": "deploy",
            "targetHost": "f5_hostname",
            "targetPort": 443,
            "targetUsername": "user",
            "targetPassphrase": "password",
            "persist": true,
            "declaration": {
              "class": "ADC",
              "schemaVersion": "3.19.0",
              "id": "Idle_Timeout_Policy",
              "smf_user_engg_005": {
                "class": "Tenant",
                "SCAI": {
                  "class": "Application",
                  "template": "generic",
                  "istio-system_istio-ingressgateway-443-tcp": {
                    "class": "Service_TCP",
                    "virtualPort": 443,
                    "virtualAddresses": [
                      "10.x.x.x"
                    ],
                    "pool": "istio-system_istio-ingressgateway-pool",
                    "profileTCP": {
                      "use": "tcp-profile"
                    }
                  },
                  "istio-system_istio-ingressgateway-pool": {
                    "class": "Pool",
                    "loadBalancingMode": "dynamic-ratio-member",
                    "monitors": [
                      "tcp"
                    ],
                    "reselectTries": 1,
                    "members": [{ "servicePort": 32001, "serverAddresses":[] }]
                  },
                  "tcp-profile": {
                    "class": "TCP_Profile",
                    "keepAliveInterval": 1800,
                    "idleTimeout": 1800
                  }
                },
                "SCAI_EXTERNAL": {
                  "class": "Application",
                  "template": "generic",
                  "istio-system_istio-ingressgateway-external-smf-eng-443-tcp": {
                    "class": "Service_TCP",
                    "virtualPort": 443,
                    "virtualAddresses": [
                      "173.x.x.x"
                    ],
                    "pool": "istio-system_istio-ingressgateway-external-smf-eng-pool",
                    "profileTCP": {
                      "use": "tcp-profile-external"
                    }
                  },
                  "istio-system_istio-ingressgateway-external-smf-eng-pool": {
                    "class": "Pool",
                    "loadBalancingMode": "dynamic-ratio-member",
                    "monitors": [
                      "tcp"
                    ],
                    "reselectTries": 1,
                    "members": [{ "servicePort": 32000, "serverAddresses":[] }]
                  },
                  "tcp-profile-external": {
                    "class": "TCP_Profile",
                    "keepAliveInterval": 1800,
                    "idleTimeout": 1800
                  }
                }
              }
            }
    }
kind: ConfigMap
metadata:
  name: examplesvs
  labels:
    as3: "true"
    f5type: virtual-server
```
2. Deploy f5-as3-container as a k8s Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: f5-as3
  name: f5-as3
  namespace: f5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: f5-as3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: f5-as3
    spec:
      containers:
      - env:
        - name: AUTH
          value: DISABLE
        image: f5-as3-container:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: f5-as3-container
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /mgmt/shared/appsvcs/available
            port: https
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

3. Create a service to expose the f5-as3-container deployment:
```
apiVersion: v1
kind: Service
metadata:
  name: f5-as3
  namespace: f5
spec:
  ports:
  - port: 443
     protocol: TCP
     targetPort: 443
  selector:
    app.kubernetes.io/name: f5-as3
  sessionAffinity: None
  type: ClusterIP
```
Run the service behind an nginx which redirects all calls for `/mgmt/shared/appsvcs/declare` to the f5-as3 service, and remaining URL's to F5 VM directly. 

4. Update the `url` property in the `bigip-login` k8s Opaque secret to point to the Cluster IP of the f5-as3 kubernetes service (or Cluster IP of the nginx ). 

5. Modify the k8s-bigip-ctlr-deployment configuration to include the following set of properties under `spec.container.args`:
```
    spec:
      containers:
      - args:
        - --credentials-directory=/etc/bigip-login
        - --bigip-partition=$(BIGIP_PARTITION)
        - --log-level=DEBUG
        - --pool-member-type=nodeport
        - --vs-snat-pool-name=
        - --agent=as3
        - --as3-validation=false
        - --insecure
        - --override-as3-declaration=namespace/examplesvs
```

### Expected Behavior
Big IP controller should generate the partition, pools, node and TCP profile using the provided AS3 declaration config map (nodes are added to pool using CIS and service discovery by labels of cis.f5.com/as3-app, cis.f5.com/as3-pool and cis.f5.com/as3-tenant labels on istio-ingressgateway of type NodePort). 

### Actual Behavior
We observe 422 response in both the Big IP controller as f5-as3-container `/var/log/restjavad-audit.0.log`: 

f5-as3-container:
```
[I][31812][28 Sep 2020 22:26:41 UTC][ForwarderPassThroughWorker] {"user":"local/svc_nonprod_user","method":"POST","uri":"http://localhost:8100/mgmt/shared/appsvcs/declare/","status":422,"from":"192.168.13.160, 192.168.9.189"}
[I][31813][28 Sep 2020 22:26:44 UTC][ForwarderPassThroughWorker] {"user":"local/svc_nonprod_user","method":"POST","uri":"http://localhost:8100/mgmt/shared/appsvcs/declare/","status":422,"from":"192.168.13.160, 192.168.9.189"}
```

k8s-big-ip-ctlr:
```
2020/09/28 22:25:07 [DEBUG] [AS3] Error handling for event
2020/09/28 22:25:07 [DEBUG] [AS3] posting request to https://10.109.75.5/mgmt/shared/appsvcs/declare/
2020/09/28 22:25:07 [ERROR] [AS3] Big-IP Responded with code: 422
2020/09/28 22:25:07 [DEBUG] [AS3] Error handling for event statusCommonResponse
```

Seeing the following errors as well in the f5-as3-container logs:
```
bash-5.0# cat /var/log/restjavad.0.log | egrep -i "error|excep|warn|fail"
[F][58][25 Sep 2020 04:20:46 UTC][8100/shared/loader LoaderWorker] Error while loading worker com.f5.rest.common.DeviceAuthTokenHelper: java.lang.NoClassDefFoundError: com/f5/mcp/schema/SchemaAttribute
Caused by: java.lang.ClassNotFoundException: com.f5.mcp.schema.SchemaAttribute
[WARNING][65][25 Sep 2020 04:20:46 UTC][PasswordUtil] Failed to find field admin in /etc/shadow
bash-5.0# cat restnoded.out
Unhandled rejection Error: Unknown endpoint path in whitelist: [object Object]
    at /usr/share/rest/node/node_modules/@f5rest/icr-odata-adapter/lib/WhitelistFilter.js:19:23
    at Array.forEach (<anonymous>)
    at WhitelistFilter.filterWithWhitelist (/usr/share/rest/node/node_modules/@f5rest/icr-odata-adapter/lib/WhitelistFilter.js:16:19)
```

When making a curl request using the AS3 declaration JSON from a pod on the cluster, the request comes back as expected:
```
root@istio-ingressgateway-external-smf-eng-585dc45df6-q9q5r:/# ./curl3.sh
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.109.75.5...
* TCP_NODELAY set
* Connected to 10.109.75.5 (10.109.75.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=Dublin; O= Software Inc.; CN=*.software.com
*  start date: Jun  6 00:00:00 2019 GMT
*  expire date: Aug 27 12:00:00 2021 GMT
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'svc_nonprod_user'
* Using Stream ID: 1 (easy handle 0x55f963c37580)
> POST /mgmt/shared/appsvcs/declare HTTP/2
> Host: 10.109.75.5
> Authorization: Basic token
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 2833
> Content-Type: application/x-www-form-urlencoded
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
< HTTP/2 301
< server: nginx/1.15.12
< date: Fri, 25 Sep 2020 23:52:28 GMT
< content-type: text/html
< content-length: 170
< location: https://10.109.75.5/mgmt/shared/appsvcs/declare/
< strict-transport-security: max-age=31536000; includeSubDomains; preload
<
* Ignoring the response-body
* Connection #0 to host 10.109.75.5 left intact
* Issue another request to this URL: 'https://10.109.75.5/mgmt/shared/appsvcs/declare/'
* Found bundle for host 10.109.75.5: 0x55f963c35020 [can multiplex]
* Re-using existing connection! (#0) with host 10.109.75.5
* Connected to 10.109.75.5 (10.109.75.5) port 443 (#0)
* Server auth using Basic with user 'svc_nonprod_user'
* Using Stream ID: 3 (easy handle 0x55f963c37580)
> POST /mgmt/shared/appsvcs/declare/ HTTP/2
> Host: 10.109.75.5
> Authorization: Basic c3ZjX25vbnByb2RfYW50aG9zOnJTRk4wMzEhNFJ0ZGk1dCQ=
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 2833
> Content-Type: application/x-www-form-urlencoded
>
* We are completely uploaded and fine
< HTTP/2 200
< server: nginx/1.15.12
< date: Fri, 25 Sep 2020 23:52:35 GMT
< content-type: application/x-www-form-urlencoded
< content-length: 1488
< x-powered-by: Express
< pragma: no-cache
< cache-control: no-store
< cache-control: no-cache
< cache-control: must-revalidate
< expires: -1
< strict-transport-security: max-age=31536000; includeSubDomains; preload
<
{"results":[{"code":200,"message":"success","lineCount":22,"host":"smf-f5-infra-mgmt.smf.uc.int","tenant":"smf_user_engg_005","runTime":4070}],"declaration":{"smf_user_engg_005":{"class":"Tenant","SCAI":{"class":"Application","template":"generic","istio-system_istio-ingressgateway-443-tcp":{"class":"Service_TCP","virtualPort":443,"virtualAddresses":["10.x.x.x"],"pool":"istio-system_istio-ingressgateway-pool","profileTCP":{"use":"tcp-profile"}},"istio-system_istio-ingressgateway-pool":{"class":"Pool","loadBalancingMode":"dynamic-ratio-member","monitors":["tcp"],"reselectTries":1,"members":[{"servicePort":32001,"serverAddresses":[]}]},"tcp-profile":{"class":"TCP_Profile","keepAliveInterval":1800,"idleTimeout":1800}},"SCAI_EXTERNAL":{"class":"Application","template":"generic","istio-system_istio-ingressgateway-external-smf-eng-443-tcp":{"class":"Service_TCP","virtualPort":443,"virtualAddresses":["173.x.x.x"],"pool":"istio-system_istio-ingressgateway-external-smf-eng-pool","profileTCP":{"use":"tcp-profile-e* Connection #0 to host 10.109.75.5 left intact
xternal"}},"istio-system_istio-ingressgateway-external-smf-eng-pool":{"class":"Pool","loadBalancingMode":"dynamic-ratio-member","monitors":["tcp"],"reselectTries":1,"members":[{"servicePort":32000,"serverAddresses":[]}]},"tcp-profile-external":{"class":"TCP_Profile","keepAliveInterval":1800,"idleTimeout":1800}}},"class":"ADC","schemaVersion":"3.19.0","id":"Idle_Timeout_Policy","updateMode":"selective","controls":{"archiveTimestamp":"2020-09-25T23:52:34.335Z"}}}
```
