### ISSUE TITLE
responseTemplate trouble with curly braces

### ISSUE THREAD

**Issue by wncocz** [F5Networks/f5-appsvcs-extension#474]
### Environment
 * Application Services Version: 3.28.0
 * BIG-IP Version: 14.1.4.1

### Summary
Curly braces in responseTemplate in Traffic_Log_Profile sometimes disappear or cause errors.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "action": "deploy",
    "persist": true,
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "id": "blah-0001",
        "schemaVersion": "3.28.0",
        "t1": {
            "class": "Tenant",
            "t1a1": {
                "class": "Application",
                "template": "generic",
                "rsp_log": {
                    "class": "Traffic_Log_Profile",
                    "responseSettings": {
                        "responseEnabled": true,
                        "responseTemplate": "foo: {{bar} :{baz} : {again}"
                    }
                }
            }
        }
    }
}
```

2. Observe the following error response:
```yaml
{
    - code: 400
      host: localhost
      message: declaration failed
      response: POST http://admin:XXXXXX@localhost:8100/mgmt/tm/sys/config merge cli script response=400 body={"code":400,"message":"incomplete command","errorStack":[],"apiError":26214401}
      runTime: 4688
      tenant: t1
}
```

### Expected Behavior
```tcl
ltm profile request-log rsp_log {
    response-log-template "foo: {{bar} :{baz} : {again}"
    response-logging enabled
}
```

OK, that one had an obvious issue with the double-left-curly-brace.  But the error is worth noting.

This case more resembles what we need to deploy:

3. Submit the following declaration:
```json
{
    "action": "deploy",
    "persist": true,
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "id": "blah-0001",
        "schemaVersion": "3.28.0",
        "t1": {
            "class": "Tenant",
            "t1a1": {
                "class": "Application",
                "template": "generic",
                "rsp_log": {
                    "class": "Traffic_Log_Profile",
                    "responseSettings": {
                        "responseEnabled": true,
                        "responseTemplate": "foo: {bar} :{baz} : {again}"
                    }
                }
            }
        }
    }
}
```

4. Observe the following error response:
```yaml
{
    - code: 200
      host: localhost
      lineCount: 18
      message: success
      runTime: 6607
      tenant: t1
}
```

### Expected Behavior
```tcl
ltm profile request-log rsp_log {
    response-log-template "foo: {bar} :{baz} : {again}"
    response-logging enabled
}
```

### Actual Behavior
The double-curly-brace gives the 400 error above.

The second declaration yields this (irrelevant properties excluded):

```tcl
ltm profile request-log rsp_log {
    response-log-template "foo: bar :{baz} : again "
    response-logging enabled
}
```

The template is missing some curly braces.
