### ISSUE TITLE
Different result for the POST call with the same AS3 JSON content

### ISSUE THREAD

**Issue by mkyrc** [F5Networks/f5-appsvcs-extension#579]
### Environment
 * Application Services Version: 3.35.0 (the same issue connected to 3.34.x)
 * BIG-IP Version: 16.1.2

### Summary

I'm using AS3 JSON for deploying services to BIGIP using Ansible. In some cases (when AS3 JSOn content is not correct from BIGIP point of view) is BIGIP's response different as expected. I'm not sure if this issue is connected to ansible module `ansible.builtin.uri` or `f5-appsvcs-extension`, but I think it's the same "POST call with the same JSON content". Maybe somebody can help me with this. I can't find the issue.

### Steps To Reproduce

1. Submit the following declaration (see '11.99.1.44' double definition that is valid separately, but not both in the same content):

```json
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.35.0/as3-schema.json",
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.35.0",
        "updateMode": "selective",
        "test-as3-01": {
            "class": "Tenant",
            "defaultRouteDomain": 5,
            "Shared": {
                "class": "Application",
                "template": "shared",
                "sf_testweb": {
                    "class": "Pool",
                    "remark": "testing pool",
                    "members": [
                        {
                            "remark": "AS3>Shared: blabla",
                            "servicePort": 8080,
                            "adminState": "enable",
                            "serverAddresses": [
                                "11.99.1.11"
                            ],
                            "servers": [
                                {
                                    "name": "rserver44",
                                    "address": "11.99.1.44"
                                }
                            ]
                        },
                        {
                            "remark": "AS3>Shared",
                            "servicePort": 8081,
                            "adminState": "enable",
                            "serverAddresses": [
                                "11.99.1.22",
                                "11.99.1.44"
                            ],
                            "servers": []
                        }
                    ]
                }
            }
        }
    }
}
```

3. Postman response is correct:
```json
    "results": [
        {
            "code": 422,
            "message": "declaration failed",
            "response": "0107176c:3: Invalid Node, the IP address 11.99.1.44%5 already exists.", 
            "host": "localhost",
            "tenant": "test-as3-01",
            "runTime": 6662
        }
    ]
```

4. Ansible call response is different (wrong):
```json
  "results": [
    {
      "code": 0,
      "message": "Declaration successfully submitted",
      "tenant": "",
      "host": "",
      "runTime": 0
    }
  ],
```

Ansible playbook for reproducing:
```yaml
    - block:
        - name: "Deploy JSON file to device (URI)"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/appsvcs/declare"
            method: POST
            body: "{{ lookup('file', JSON_FILE ) }}" # << this is absolute path to JSON file
            body_format: json
            status_code: [200, 201, 202, 422]
            timeout: 300
            return_content: true
            force_basic_auth: yes
            user: "{{ provider.user }}"
            password: "{{ provider.password }}"
            validate_certs: "{{ provider.validate_certs }}"
          register: DEPLOY_RESULT
          failed_when: DEPLOY_RESULT.status != 200
          tags:
            - deploy-debug
            - deploy

      rescue:
        - name: "(debug) ERROR: Deploy error"
          debug:
            msg:
              - "RESULTS: {{ DEPLOY_RESULT }}"
          tags:
            - deploy-debug

        - name: "ERROR: Deploy error"
          debug:
            msg:
              - "msg: {{ DEPLOY_RESULT.msg }}"
              - "results: {{ DEPLOY_RESULT.json.results }}"
          tags:
            - deploy-debug
            - deploy

```

### Expected Behavior
The expected is the same result from Postman and Ansible (in both cases it is "the same URI call with the same content").

### Actual Behavior
Postman's result and Ansible result's is different in case of 'incorrect' AS3 content. When the content of AS3 JSON is correct, both answers (Postman and Ansible) are the same (correct) result.

**Comment by dstokesf5** [comment]
This appears to be a problem with the Ansible module and not AS3. Please file an issue with the Anisble module.

**Comment by mkyrc** [comment]
> This appears to be a problem with the Ansible module and not AS3. Please file an issue with the Anisble module.

@dstokesf5 you are wrong in this case (see my second issue below). That's not "Ansible module issue". I'd like to share my investigation with other users here.

After some investigation I can confirm two issues on big-ip side. In both cases I'm playing with (very simple - only one pool with two members) correct AS3 configuration. You can find results below.

### First issue - code 202

Bigip response to POST from Postman and Ansible is code 202 with "declaration successfullu submited", no tenant, no host - BUT no change is made to bigip. That's wrong. See result:

```json
  "results": [
    {
      "code": 0,
      "message": "Declaration successfully submitted",
      "tenant": "",
      "host": "",
      "runTime": 0
    }
  ]
```

Solution: 
bigip restart (restarting only restjavad or other services connected to REST was not helpful).

Note:
This "code 202, with declaration success, with no host and no tenant" is common for cases of trouble on bigip side. tcpdump on bigip shows "no declaration content" coming to "rest engine" (the same for postman and/or ansible). I think bigip was in "some strange state". After reboot is situation fixed. I have open service request on f5 support for this.

### Second issue - Ansible with http basic authentication

REST calls authentication is possible by two ways:
1. http basic authentication method
2. token-based authentication

Both methods are working with **local defined user** (for Postman and Ansible with builtin.uri module described above). This is very common example on f5 labs. But for **external user** (authentication against tacacs/radius/...) is HTTP Basic **not** working! That's the core issue with Ansible module 'uri'. 

This is confirmed by Postman - basic authentication with external user is not working. We are using 'netops user' defined on tacacs and therefore is our ansible call failing. I can't confirm, if it starts failing after upgrade f5-appsvc to latest version 3.35.0, but I think before (3.34.0) it was working (we need 3.35.0, because we need names for pool members and this feature is supported starting 3.35.0).

Solution:
Changing Ansible task from http basic to token based authentication is the solution. Now, is playbook's task with 'ansible.builtin.uri' module for POST-ing AS3 content working correctly (with token for authentication).

### Ansible playbook with token based authentication here (Maybe for somebody can be helpful)

```yaml
    - block:
        - name: "Get auth token"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/authn/login"
            method: POST
            body: '{"username": "{{provider.user}}", "password": "{{provider.password}}", "loginProviderName": "tmos" }'
            body_format: json
            status_code: [200]
            timeout: 20
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          register: AUTH_RESULT
          failed_when: AUTH_RESULT.status != 200
          check_mode: no

        - name: "DEBUG: Auth token"
          debug:
            msg:
              - "token:  {{ AUTH_RESULT.json.token.token }}"

        - name: "Token timeout to 5 min"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/authz/tokens/{{AUTH_RESULT.json.token.token}}"
            method: PATCH
            body: '{ "timeout":"300" }'
            body_format: json
            headers:
              X-F5-Auth-Token: "{{ AUTH_RESULT.json.token.token }}"            
            status_code: [200]
            timeout: 20
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          check_mode: no          

      when:
        - active_member is defined
        - active_member == true

      rescue:
        - name: "ERROR: Authentication fail"
          debug:
            msg:
              - "status:  {{ AUTH_RESULT.status }}"
              - "results: {{ AUTH_RESULT.json }}"

    - block:

        - name: "Deploy JSON file to device (URI)"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/appsvcs/declare?controls.dryRun={{ansible_check_mode}}"
            method: POST
            body: "{{ lookup('file', JSON_FILE ) }}"
            headers:
              X-F5-Auth-Token: "{{ AUTH_RESULT.json.token.token }}"
            body_format: json
            status_code: [200]
            timeout: 300
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          register: DEPLOY_RESULT
          failed_when: DEPLOY_RESULT.status != 200
          # no_log: true
          check_mode: no
          when:
            - active_member is defined
            - active_member == true
            - AUTH_RESULT.json.token.token is defined

        - name: "OK: Deploy result"
          debug:
            msg:
              - "status:  {{ DEPLOY_RESULT.status }}"
              - "msg:     {{ DEPLOY_RESULT.msg }}"
              - "results: {{ DEPLOY_RESULT.json.results }}"
          when:
            - active_member is defined
            - active_member == true
            - DEPLOY_RESULT.status is defined and DEPLOY_RESULT.status == 200

      rescue:
        - name: "(debug) ERROR: Deploy error"
          debug:
            msg:
              - "RESULTS: {{ DEPLOY_RESULT }}"

        - name: "ERROR: Deploy error"
          debug:
            msg:
              - "status:  {{ DEPLOY_RESULT.status }}"
              - "msg:     {{ DEPLOY_RESULT.msg }}"
              - "results: {{ DEPLOY_RESULT.json }}"

# good solution is to delete auth token after deploying AS3 content. 
# I this case is timeout shorten from 1200sec (10 mins) to 600sec (5min) without deleting token by ansible.
```

**Comment by dstokesf5** [comment]
A 202 status code means AS3 has accepted the request, but is still processing it. It looks like what you are seeing is AS3 switching from synchronous processing to asynchronous processing. It does that to avoid timeouts imposed by restnoded and/or restjavad.

From the [Warnings, Notes, & Tips page](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/tips-warnings.html):
>Even if you have asynchronous mode set to false, after 45 seconds AS3 sets asynchronous mode to true (API swap), and returns an async response. This allows you to use GET to poll for status (you should see a 202 status until the declaration is complete). This typically occurs only with very large declarations or most declarations to BIG-IQ; if the declaration completes in less than 45 seconds, AS3 does not modify asynchronous mode. 

API documentation for more information on 202 status code responses: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/apidocs.html#tag/Configuration

**Comment by mkyrc** [comment]
Daniel, thank you for this! Good to know details about code 202. It's very helpful for me. Do you think, is there any reason to (always) POST declaration with pre-set async=true parameter? Is there any reason or benefit to prefer async=true against (default) async=false?

Maybe you are right and AS3 switched to async mode after 45 seconds (but in my case is AS3 content for test reason very short). Currently is hard to confirm it, but I changed my playbook - added new task after existing 'deploy'. It works very well - when response (from deploy task) is code 202, new task will wait and periodically check task by task ID until "success" (or response code != 200 or 202).

This is the additional task (initial `DEPLOY_RESULT` is coming from previous 'deploy' task):

```yaml
        - name: "{{pb_prfx}}-03-03: Wait for async result"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/appsvcs/task/{{DEPLOY_RESULT.json.id}}?controls.dryRun={{ansible_check_mode}}"
            method: GET
            headers:
              X-F5-Auth-Token: "{{ AUTH_RESULT.json.token.token }}"
            status_code: [200, 202]
            timeout: 300
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          register: DEPLOY_RESULT
          failed_when: DEPLOY_RESULT.status != (200 or 202)
          until: DEPLOY_RESULT.json.results.0.message == "success"
          retries: 5
          delay: 10
          no_log: true
          check_mode: no
          tags:
            - deploy
            - deploy-debug          
          when:
            - active_member is defined
            - active_member == true
            - DEPLOY_RESULT.status is defined and DEPLOY_RESULT.status == 202
            - DEPLOY_RESULT.json.id is defined

        - name: "OK: Deploy result (after async wait)"
          debug:
            msg:
              - "status:  {{ DEPLOY_RESULT.status }}"
              - "msg:     {{ DEPLOY_RESULT.msg | default('') }}"
              - "results: {{ DEPLOY_RESULT.json.results | default('') }}"
              - "id:      {{ DEPLOY_RESULT.json.id | default('') }}"
          when:
            - active_member is defined
            - active_member == true
            - DEPLOY_RESULT.status is defined 
            - DEPLOY_RESULT.status == 200
```
