### ISSUE TITLE
Unable to define device name for GSLB_Server object

### ISSUE THREAD

**Issue by mkyrc** [F5Networks/f5-appsvcs-extension#855]
### Is your feature request related to a problem?
By using AS3 is not possible to define device name within GSLB Server configuration. After AS3 deployment is the device name created as sequence nr (0, 1, 2, etc) and in the GUI it is not so clear what's the device. 

AS3 definition example:
```yaml
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/v3.46.0/schema/3.46.0/as3-schema.json",
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.46.0",
        "id": "test-gslb-server",
        "updateMode": "selective",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "dc1": {
                    "class": "GSLB_Data_Center"
                },
                "test_bigip_server": {
                    "class": "GSLB_Server",
                    "dataCenter": {
                        "use": "dc1"
                    },
                    "exposeRouteDomainsEnabled": false,
                    "enabled": true,
                    "devices": [
                        {
                            "address": "10.20.30.41"                         
                        },
                        {
                            "address": "10.20.30.42"
                        }
                    ],
                    "virtualServerDiscoveryMode": "enabled"
                }
            }
        }
    }
}
````

By using GUI is possible define it with device name, not only IP address:
![image](https://github.com/user-attachments/assets/f5e14319-1368-4d9a-8b57-2c17dd194533)

### Describe the solution you'd like
It will be nice to have possibility to define device name, not only IP address with AS3.

AS3 example (only part of GSLB_Server definition) whre the change is required:

```yaml
"test_bigip_server": {
                    "class": "GSLB_Server",
                    "dataCenter": {
                        "use": "dc1"
                    },
                    "exposeRouteDomainsEnabled": false,
                    "enabled": true,
                    "devices": [
                        {
                            "name": "bigip-device-01", <<< here
                            "address": "10.20.30.41"                         
                        },
                        {
                            "name": "bigip-device-02", <<< here
                            "address": "10.20.30.42"
                        }
                    ],
                    "virtualServerDiscoveryMode": "enabled"
                }
```
