### ISSUE TITLE
virtualAddresses w/mask plus shareAddresses true not idempotent

### ISSUE THREAD

**Issue by wncocz** [F5Networks/f5-appsvcs-extension#872]
### Environment
 * Application Services Version: 3.49.0 and 3.52.0
 * BIG-IP Version: 15.1.10.3

### Summary
If a (non-/32) subnet mask is specified on virtualAddresses, and shareAddresses is true, re-posting an already-deployed declaration fails with error.  Observed similar behavior whether the virtualAddress is 0.0.0.0/0, 192.168.0.0/16, or 10.13.13.0/24

### Steps To Reproduce
1. Submit the following declaration:
```json
{
	"class": "ADC",
	"id": "test-0001",
	"schemaVersion": "3.49.0",
	"test": {
		"class": "Tenant",
		"test": {
			"class": "Application",
			"template": "generic",
			"test_fwd24": {
				"class": "Service_Forwarding",
				"forwardingType": "ip",
				"layer4": "udp",
				"allowVlans": [{ "bigip": "/Common/VLAN13" }],
				"profileL4": { "bigip": "/Common/fastL4" },
				"snat": { "use": "test_snat" },
				"virtualAddresses": [
					[ "10.13.13.0/24", "10.12.12.0/23" ]
				],
				"shareAddresses": true,
				"virtualPort": 3999
			},
			"test_snat": {
				"class": "SNAT_Pool",
				"snatAddresses": [
					"10.12.12.12"
				]
			}
		}
	}
}
```
2. Observe successful deployment
3. Submit it again
4. Observe the following error response:
```yaml
    results:
    - code: 422
      declarationId: test-0001
      host: localhost
      message: declaration failed
      response: '01020036:3: The requested virtual address (/Common/10.13.13.0/24) was not found.'
      runTime: 12647
      tenant: test
```

### Expected Behavior
Subsequent deployments should succeed without error (or change).

### Actual Behavior
Observed error occurs
